services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d study"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: techzone-redis
    restart: always
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.2

    container_name: techzone-redpanda

    command:
    - redpanda
    - start
    - --overprovisioned
    - --smp=1
    - --memory=1G
    - --reserve-memory=0M
    - --node-id=0
    - --check=false
    - --kafka-addr=PLAINTEXT://0.0.0.0:9092
    - --advertise-kafka-addr=PLAINTEXT://redpanda:9092

    ports:
      - "9092:9092"

    volumes:
      - redpanda_data:/var/lib/redpanda/data
    
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  notification:
    build:
      context: .
      dockerfile: Dockerfile.notification

    container_name: techzone-notification

    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy

    environment:
      DB_URL: postgres://postgres:1234@postgres:5432/study?sslmode=disable
      KAFKA_BROKERS: redpanda:9092

    ports:
    - "50051:50051"

  prometheus:
    image: prom/prometheus:latest
    container_name: techzone-prometheus

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

    depends_on:
      - app
      - notification

  grafana:
    image: grafana/grafana:latest
    container_name: techzone-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

    restart: unless-stopped

  app:
    build: .
    container_name: techzone-app
    depends_on:
      postgres:
        condition: service_healthy
      
      redis:
        condition: service_healthy

      redpanda:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_URL: postgres://postgres:1234@postgres:5432/study?sslmode=disable
      REDIS_ADDR: redis:6379
      KAFKA_BROKERS: redpanda:9092
      NOTIFICATION_GRPC_ADDR: notification:50051

volumes:
  postgres_data:
  redis_data:
  redpanda_data:
  grafana-data: