services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      DB_URL: "postgres://postgres:1234@postgres:5432/study"

volumes:
  postgres_data: