apiVersion: v1
kind: ConfigMap

metadata:
  name: techzone-config
  namespace: techzone

data:
  DB_HOST: postgres
  DB_PORT: "5432"
  POSTGRES_DB: study
  POSTGRES_USER: postgres

  REDIS_ADDR: redis:6379

  KAFKA_BROKERS: kafka:9092

  NOTIFICATION_GRPC_ADDR: notification:50051