name: TechZone CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Install Goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Start infrastructure
        run: docker compose up -d postgres redis redpanda

      - name: Wait for containers
        run: sleep 20

      - name: Run migrations
        env:
          DB_URL: postgres://postgres:1234@localhost:5432/study?sslmode=disable
        run: make migrate-up

      - name: Run unit tests
        run: make unit

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.10.1
          args: ./cmd/... ./internal/... ./pkg/... ./tests/...

      - name: Run integration tests
        env:
          DB_URL: postgres://postgres:1234@localhost:5432/study?sslmode=disable
          REDIS_ADDR: localhost:6379
          KAFKA_BROKERS: localhost:9092
        run: make integration

      - name: Build Docker image
        run: docker build -t techzone .